### PR TITLE
Update dependencies to get upstream fixes, namely to make this bridge work again

### LINKED ISSUE #41: Can not link; Unhandled Promise Rejection: Error: Already logged on, cannot log on again
Hello
I'm trying to set up mx-puppet-steam but I've been working on it for hours now and I simply can not get it to link to my Steam account. The bot responds to me and I can issue the link command, I have Steam guard enabled on my mobile it pops up the code and I provide the code, but then nothing happens. The bot goes silent for a few moments and then just pretends like nothing happened / not linked. The console spits the error below if I send the bot any messages during the silent duration.

Errors in the mx-puppet-steam console output:
````
Mar-13 06:43:39.002 [PuppetBridge] error: Unhandled Promise Rejection: Error: Already logged on, cannot log on again
    at /opt/mx-puppet-steam/node_modules/steam-user/components/logon.js:23:10
    at processTicksAndRejections (node:internal/process/task_queues:76:11)

Mar-13 06:43:39.002 [PuppetBridge] error: Promise {
  <rejected> Error: Already logged on, cannot log on again
      at /opt/mx-puppet-steam/node_modules/steam-user/components/logon.js:23:10
      at processTicksAndRejections (node:internal/process/task_queues:76:11)
}
````

As well as several of these all the time:
`Mar-13 06:46:46.011 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!`

But what is confusing to me is that I don't seem to be getting any log messages from the src/steam.ts events should be "MatrixPuppet:Steam" but I get none of those in my console output (turned up to silly), at all.. And those seem like they'd be the most useful log entries :(

Any help would be greatly appreciated!

### PR DESCRIPTION
**Pull request by plantroon**
This fixes #41

### CODE REVIEW

**Comment by plantroon** [comment]
It contains fixes by dependabot to the other PRs in this repo.

Within this PR I added docker-publish workflow as well, not sure if that is desirable but I don't see any harm in it.

**Comment by JokerGermany** [comment]
I don't know if @icewind1991 will react, perhaps it's the best, to fork the project...

**Comment by plantroon** [comment]
> I don't know if @icewind1991 will react, perhaps it's the best, to fork the project...

Am I worthy? The tiny work I did is just a little more than what dependabot does and he goes ignored usually :D

**Comment by icewind1991** [comment]
Thanks!

**Pull request merged**
